---
title: "Daily Drop WPE: Plot"
format: html
theme:
  light: flatly
  dark: darkly
---

```{r}
ojs_define(mpgR = ggplot2::mpg)
ojs_define(mtcarsR = tibble::rownames_to_column(mtcars, "vehicle"))
ojs_define(diamondsR = ggplot2::diamonds)
ojs_define(faithfuldR = ggplot2::faithfuld)
ojs_define(faithfulR = faithful)
ojs_define(economicsR = ggplot2::economics)
ojs_define(economicsLongR = ggplot2::economics_long)
```

```{ojs}
mpg = transpose(mpgR)
mtcars = transpose(mtcarsR)
diamonds = transpose(diamondsR);
faithfuld = transpose(faithfuldR);
faithful = transpose(faithfulR);
economics = transpose(economicsR);
economicsLong = transpose(economicsLongR);

defaultStyle = ({
	backgroundColor: "#00000000",
})
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	marks: [Plot.text(mtcars, { x: "wt", y: "mpg", text: "vehicle" })],
});
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	marks: [
		Plot.text(
			mtcars,
			{ x: "wt", y: "mpg", text: "vehicle", fontSize: "14pt" }
		)
	]
})
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	marks: [
		Plot.dot(
			mtcars,
			{ x: "wt", y: "mpg", fill: "#3a579a" }
		),
		Plot.text(
			mtcars,
			{ x: d => d.wt + 0.05, y: "mpg", text: "vehicle", textAnchor: "start" }
		)
	]
})
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	marks: [
		Plot.dot(
			mtcars,
			{ x: "wt", y: "mpg", fill: "#3a579a" }
		),
		Plot.text(
			mtcars,
			{ x: "wt", y: d => d.mpg + 0.75, text: "vehicle", textAnchor: "middle" }
		)
	]
})
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	marks: [
		Plot.dot(
			mtcars,
			{ x: "wt", y: "mpg", fill: "#3a579a" }
		),
		Plot.text(
			mtcars,
			{ x: "wt", y: "mpg", text: "vehicle", rotate: -45}
		)
	]
})
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	color: {
		type: "ordinal",
		range: [ "#88a2bc", "#d99477", "#586c5c"],
		legend: true
	},
	marks: [
		Plot.text(
			mtcars.map(d => { d.cyl = `${d.cyl}`; return d }),
			{ x: "wt", y: "mpg", text: "vehicle", fill: "cyl" }
		)
	]
})
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	marks: [
		Plot.text(
			mtcars,
			{ x: "wt", y: "mpg", text: "vehicle", fontSize: d => d.wt * 2 * Math.sqrt(d.wt) }
		)
	]
})
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	marginLeft:100,
	marks: [
		Plot.dot(
			diamonds,
			{ x: "carat", y: "price", opacity: 1/10}
		)
	]
})
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	marks: [
		Plot.boxY(
			mpg, 
			{ x: "class", y: "hwy" }
		)
	],
});
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	marks: [
		Plot.dot(mpg, { x: "displ", y: "hwy" }),
		Plot.linearRegressionY(mpg, {
			x: "displ",
			y: "hwy",
			stroke: "red",
		}),
	],
});
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	marginLeft: 50,
	marginBottom:50,
	marks: [
		Plot.hexgrid(),
		Plot.dot(
			diamonds,
			Plot.hexbin(
				{ r: "count" },
				{ x: "carat", y: "price", fill: "currentColor" }
			)
		),
	],
})
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	marginLeft: 50,
	marginBottom: 50,
	marks: [
		Plot.density(faithful, { x: "eruptions", y: "waiting" }),
		Plot.dot(faithful, { x: "eruptions", y: "waiting" }),
	],
});
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	marks: [Plot.line(economics, { x: "date", y: "unemploy" })],
});
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	color: {
		legend: true,
	},
	marks: [
		Plot.line(economicsLong, { x: "date", y: "value01", stroke: "variable" }),
	],
});
```

```{ojs}
Plot.plot({
	style: defaultStyle,
	grid: true,
	color: {
		legend: true,
	},
	marks: [
		Plot.line(
		economics.map(d => { d.date = new Date(d.date); return d }), 
		{
			x: (d) => d.unemploy / d.pop,
			y: "psavert",
			z: null,
			stroke: "date"
		}),
	],
});
```

```{ojs}
Plot.plot({
		style: defaultStyle,
		grid: true,
		color: {
			legend: true
		},
		marks: [
			Plot.dot(mtcars, { x: "wt", y: "mpg" }),
			Plot.link([ { x1: 2.62, x2: 3.57, y1: 21.0, y2: 15.0 } ], {
				x1: "x1",
				x2: "x2",
				y1: "y1",
				y2: "y2"
			})
		]
	})
```

<div id="manual-01"></div>

<div id="manual-02"></div>

<div id="manual-03"></div>

<div id="manual-04"></div>

<script type="module">
import * as Plot from "https://cdn.jsdelivr.net/npm/@observablehq/plot@latest/+esm";
import * as d3 from "https://cdn.jsdelivr.net/npm/d3@latest/+esm";

const mtcars = await d3.csv("./mtcars.csv", d3.autoType);
const mpg = await d3.csv("./mpg.csv", d3.autoType);
const faithfuld = await d3.csv("./faithfuld.csv", d3.autoType);

const manual01 = document.getElementById("manual-01")
const manual02 = document.getElementById("manual-02")
const manual03 = document.getElementById("manual-03")
const manual04 = document.getElementById("manual-04")

const defaultStyle = {
	backgroundColor: "#00000000",
}

manual01.replaceChildren(
	Plot.plot({
		style: defaultStyle,
		y: {
			grid: true,
		}, 
		marks: [
			Plot.auto(mpg, { x: "class", y: { reduce: "count" }, mark: "bar" })
		]
	})
)

manual02.replaceChildren(
	Plot.plot({
		style: defaultStyle,
		y: {
			grid: true,
		},
		marks: [
			Plot.auto(mpg, { y: "class", x: { reduce: "count" }, mark: "bar" })
		]
	})
)

manual03.replaceChildren(
	Plot.plot({
		style: defaultStyle,
		color: {
			legend: true
		},
		y: {
			grid: true,
		},
		marks: [
			Plot.auto(mpg, { x: "class", y: { reduce: "count" }, color: "drv", mark: "bar" })
		]
	})
)

manual04.replaceChildren(
	Plot.plot({
		style: defaultStyle,
		marks: [
			Plot.raster(
				faithfuld,
				{ x: "waiting", y: "eruptions", fill: "density", interpolate: "nearest"}
			)
		]
  })
)
</script>


<style>
[class*="plot-"] {
	background: none;
	background-color: #00000000;
}
</style>
